name: Pull request version check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  versionCheck:
    name: Pull request version number validation
    runs-on: ubuntu-latest
    steps:
      - id: version
        name: Get the version number
        run: |
          v=`echo $github.event.pull_request.title | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/'`
          if [ "$version" = "$v" ]; then
            exit 1;
          else
            echo $v;
          fi
        env:
          version: ${{ inputs.version_checker }}

  releaseVersion:
    name: Release Version
    runs-on: ubuntu-latest
    needs: versionCheck
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Grant Permission for properties
        run: chmod +x properties_read.sh

      - name: CheckVersion
        run: ./properties_read.sh

      - name: Show Version name
        run: echo ${{env.GITHUB_SDK_VERSION}}
