name: Pull request version check

on:
  push:
    branches:
      - main
      - master
jobs:
  releaseVersio:
    name: Release Version
    runs-on: ubuntu-latest
    steps:
      - name: Grant Permission for properties
        run: chmod +x properties_read.sh

      - name: CheckVersion
        run: ./properties_read.sh

      - name: Show Version name
        run: echo ${{env.SDK_VERSION}}