name: Release production SDK
on:
  push:
    branches:
      - main
    paths:
      - version.properties

jobs:
  publish:
    name: Publishing SDK
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Grant Permission for properties
        run: chmod +x properties_read.sh

      - name: CheckVersion
        run: ./properties_read.sh

      - name: Show Version name
        run: echo v${{env.GITHUB_SDK_VERSION}}

      - name: Update Internal Library
        run: |
          git config --global user.email "robot@neuro-id.com"
          git config --global user.name "robot"
          git tag -a v${{env.GITHUB_SDK_VERSION}} -m "Neuro-ID Android SDK Version: ${{env.GITHUB_SDK_VERSION}}"
          git push

      - name: Create Release ✅
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.GITHUB_SDK_VERSION }}
          release_name: v${{ env.GITHUB_SDK_VERSION }}
          draft: false
          prerelease: false
